version: '3.8'

volumes:
  postgres_data:
  staticfiles:


services:
  db:
    image: postgres:13
 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env
      
      
  web:

    build: .
    volumes:
      - staticfiles:/app/static/

    restart: always
    ports:
      - '8000:8000'

    depends_on:
      - db
    env_file:
      - ./.env 
  
  web1:
    image: nginx:1.19.6
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/app/static/

    restart: always
    ports:
      - '80:80'
    depends_on:
      - web
