# Generated by Django 2.2 on 2021-04-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='дата новости')),
                ('header', models.CharField(max_length=50, verbose_name='заголовок новости')),
                ('text', models.TextField(verbose_name='текст новости')),
            ],
        ),
    ]
